Create-Item:
  - AMETHYST_SHARD
Activate-Item:
  - ENDER_PEARL
Locked-Networks:
  ModNetwork: none
  AdminNetwork: tpritual.adminnetwork
Seperate-Drop-Items: true
Using-Title: '&c(here)'
Locked-Network-Deny: '&cYou can not use this network - insufficient perms'
Not-Created: '&cYou must create the ritual before activating it!'
Ritual-Created: '&aRitual has successfully been created!'
Not-In-Middle: '&cYou must be in the center of the ritual to teleport!'
Not-While-Using: '&cYou can not do this while you are using a Ritual!'
No-Create-Perms: '&cYou do not have permission to create rituals!'
No-Use-Perms: '&cYou do not have permission to use rituals!'
No-Use-Other-Perms: '&cYou do not have permission to use rituals not owned by you!'
No-Endereye-Travel-Perms: '&cYou do not have permission to fast travel!'
No-Ritual-Travel: '&cThis ritual does not have any rituals to travel to!'
Hit-Creation-Limit: '&cYou have the max number of rituals! You must remove one first.'
Activate-Ritual: '&aSuccessfully activated ritual!'
Already-Active: '&cThis ritual is already active!'
Already-Created: '&aThis ritual has already been created! You must activate it instead!'
Already-Using: '&cYou can only use one ritual at a time!'
Deactivated-Ritual: '&cSuccessfully deactivated ritual'
Removed-Ritual: '&cSuccessfully removed ritual'
Teleporting: '&aTeleporting in %seconds%.. please wait.'
Ritual-Timeout: 20 # in seconds
Teleport-Delay: 6 # in seconds
Debug: false
Update-Check: true