name: TPRituals
version: 1.7
api-version: 1.13
main: me.mehboss.ritual.Main
author: mehboss
description: A custom coded Ritual teleport plugin inspired by Perasha and requested by KittyKit
softdepend: [Multiverse-Core]